### ISSUE TITLE
Fail to run "final_evaluation_m2t.py"

### ISSUE THREAD

**Issue by Garfield-kh** [EricGuo5513/TM2T#2]
Firstly of all, thank you for sharing such an interesting work!

I have a question on the final evaluation:
When I try the `python final_evaluation_m2t.py `, 
I met a error message: `FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/t2m/Comp_v6_KLD005/opt.txt'`
I found the config name `Comp_v6_KLD005` in your previous work [text-to-motion](https://github.com/EricGuo5513/text-to-motion/blob/0a3253d7cd33ee3ea782c3d4e8d8923634aa7b7d/final_evaluations.py#L273).
Is there any modification I need to do to make it runable?

**Comment by Garfield-kh** [comment]
btw, I think there might be some typo error in the README.md:
there are two `Evaluating Motion2Text` under `Quantitative Evaluations` 
the `--n_enc_rs 4` might be `--n_enc_layers 4` under `Translating motions into langauge (using test set) With Beam Search:`

**Comment by EricGuo5513** [comment]
> Firstly of all, thank you for sharing such an interesting work!
> 
> I have a question on the final evaluation: When I try the `python final_evaluation_m2t.py `, I met a error message: `FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/t2m/Comp_v6_KLD005/opt.txt'` I found the config name `Comp_v6_KLD005` in your previous work [text-to-motion](https://github.com/EricGuo5513/text-to-motion/blob/0a3253d7cd33ee3ea782c3d4e8d8923634aa7b7d/final_evaluations.py#L273). Is there any modification I need to do to make it runable?

Hi, "./checkpoints/t2m/Comp_v6_KLD005/opt.txt" should already be provided in the checkpoint unzip file. If you keep the checkpoint file untouched, it is supposed to be here. I use it because it contains configuration for text-motion-matching model. Would you mind having a check on that?

**Comment by EricGuo5513** [comment]
> btw, I think there might be some typo error in the README.md: there are two `Evaluating Motion2Text` under `Quantitative Evaluations` the `--n_enc_rs 4` might be `--n_enc_layers 4` under `Translating motions into langauge (using test set) With Beam Search:`

Thanks for correction. Has been revised :).

**Comment by Garfield-kh** [comment]
> > Firstly of all, thank you for sharing such an interesting work!
> > I have a question on the final evaluation: When I try the `python final_evaluation_m2t.py `, I met a error message: `FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/t2m/Comp_v6_KLD005/opt.txt'` I found the config name `Comp_v6_KLD005` in your previous work [text-to-motion](https://github.com/EricGuo5513/text-to-motion/blob/0a3253d7cd33ee3ea782c3d4e8d8923634aa7b7d/final_evaluations.py#L273). Is there any modification I need to do to make it runable?
> 
> Hi, "./checkpoints/t2m/Comp_v6_KLD005/opt.txt" should already be provided in the checkpoint unzip file. If you keep the checkpoint file untouched, it is supposed to be here. I use it because it contains configuration for text-motion-matching model. Would you mind having a check on that?

Thank you for the reminding, I just notice that I was trained from scratch, that's why the opt.txt is not included. 
By copying them from the zip file, everything works fine and result is quite similar to the paper reported.
Thank you!
