### ISSUE TITLE
DataError

### ISSUE THREAD

**Issue by wang-zm18** [EricGuo5513/TM2T#5]
When I use "evaluate_m2t_transformer.py" to evaluate the pretrained model on KIT dataset, it occurs this error:
          No such file or directory: './dataset/KIT-ML/VQVAEV3_CB1024_CMT_H1024_NRES3/02346.txt'
I found that the "texts" folder contains a series of *.txt files, I correct the correpsonding codes about data acquisition in "dataset.py" in Line 538 (opt.m_token_dir -> opt.text_dir), it occurs this error:
![image](https://user-images.githubusercontent.com/47704679/189031737-3300f46f-f0a9-47ba-9fb0-5921b48916fa.png)

**Comment by EricGuo5513** [comment]
Hi, actually you should use "opt.m_token_dir" instead of "opt.text_dir". Before you run "evaluate_m2t_transformer.py", please make sure that you have run "tokenize_script.py".

**Comment by wang-zm18** [comment]
OK, thank you for your reply!
