### ISSUE TITLE
How to convert a matchmaker to a 3D person

### ISSUE THREAD

**Issue by changleilei** [EricGuo5513/TM2T#9]
Hi, Thanks for your awesome work! and how to convert 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/32992337/209625863-11657f50-e4a1-4817-803b-7f58c88ce8de.png">
to 
<img width="114" alt="image" src="https://user-images.githubusercontent.com/32992337/209626104-157254cf-5b17-4605-abaf-8d86d4cb3f7e.png">
any suggestion? Thank you.

**Comment by EricGuo5513** [comment]
Hello,

The work "Human Motion Diffusion Model" generates the same data as us, you
could follow their steps to get SMPL parameters and 3D animation.
https://github.com/GuyTevet/motion-diffusion-model

Best,

Chuan

**Comment by changleilei** [comment]
Ok, I got it,Thank you !!
